final Map<String, String> intlEnId = {
  "title":"首页",
  "setting language":"设置语言",
  "en":"英文",
  "cn":"简体",
  "hk":"繁体",
  '欢迎登录FUJL': "欢迎登录FUJL（印尼）",

'投资': 'Investasi',
'邀请': 'Undang',
'我的': 'Saya',
'AI理财': 'Keuangan AI',
'节点': 'Node',
'挖矿': 'Tambang',
'闪兑': 'Tukar',
'团队': 'Tim',
'客服': 'Bantuan Pelanggan',

'智能理财': 'Pengelolaan Cerdas',
'最大利率': 'Suku Bunga Maksimal',
'预计年化': 'Estimasi Tingkat Tahunan',
'申购限额': 'Batas Pembelian',
'申购': 'Beli',

  // 申购
'第一期': 'Periode Pertama',
'起息日期': 'Tanggal Mulai Bunga',
'申购额度': 'Batas Pembelian',
'倍数起': 'Kelipatan Awal',
'全部': 'Semua',
'账户余额': 'Saldo Akun',
'勾选并同意': 'Centang dan Setujui',
'利息奖励': 'Penghargaan Bunga',
'确认申购': 'Konfirmasi Pembelian',
'温馨提示': 'Catatan Penting',
'是否确认申购': 'Apakah Anda yakin ingin membeli?',
'智能理财产品': 'Produk Pengelolaan Cerdas',
'取消': 'Batal',
'确认': 'Konfirmasi',
'申购额度格式不能为空': 'Format Batas Pembelian tidak boleh kosong',
'申购额度应大于': 'Batas Pembelian harus lebih dari',
'或小于': 'atau kurang dari',
'申购额度应小于': 'Batas Pembelian harus kurang dari',
'格式不正确': 'Format tidak benar',
'恭喜您申购成功': 'Selamat, pembelian Anda berhasil',
'选择币种': 'Pilih Mata Uang',
'AIT资产': 'Aset AIT',
'已确认': 'Dikonfirmasi',
'账单明细': 'Rincian Tagihan',
'AIT钱包余额': 'Saldo Dompet AIT',
'提示：1AIT=1USDT': 'Catatan: 1AIT=1USDT',
'总收益(AIT)': 'Total Penghasilan (AIT)',
'昨日收益（AIT）': 'Penghasilan Kemarin (AIT)',
'剩余总量(AIT)': 'Jumlah Sisa (AIT)',
'销毁数量（AIT）': 'Jumlah Dihancurkan (AIT)',
'AIC账单': 'Rincian Tagihan AIC',
'全部月份': 'Semua Bulan',
'收入/支出': 'Pemasukan/Pengeluaran',

'节点认购': 'Langganan Node',
'AIC挖矿': 'Penambangan AIC',
'联系客服': 'Hubungi Layanan Pelanggan',

'邀请记录': 'Catatan Undangan',
'累计邀请好友': 'Total Teman yang Diundang',
'被邀请人': 'Orang yang Diundang',
'等级': 'Level',
'注册时间': 'Waktu Pendaftaran',
'名': 'Nama',
'查看更多': 'Lihat Selengkapnya',

'暂定的banner': 'Banner Sementara',
'收益明细': 'Rincian Pendapatan',
'理财账户估值': 'Estimasi Nilai Akun Keuangan',
'理财⾦额（USDT）': 'Jumlah Dana Pengelolaan (USDT)',
'收益（AIT）': 'Pendapatan (AIT)',
'投资记录': 'Catatan Investasi',

'收益名称': 'Nama Pendapatan',
'当前收益': 'Pendapatan Saat Ini',
'收益时间': 'Waktu Pendapatan',
'币种': 'Mata Uang',
'当前利率': 'Suku Bunga Saat Ini',
'总收益': 'Total Pendapatan',
'本金': 'Modal',
'起息日': 'Tanggal Mulai Bunga',
'状态': 'Status',

'推荐收益': 'Pendapatan Rekomendasi',
'分红收益': 'Pendapatan Dividen',
'租赁收益': 'Pendapatan Sewa',
'节点收益': 'Pendapatan Node',
'分享收益': 'Pendapatan Berbagi',
'团队收益': 'Pendapatan Tim',
'我的收益明细': 'Rincian Pendapatan Saya',

'我的团队': 'Tim Saya',
'当前级别': 'Level Saat Ini',
'团队人数': 'Jumlah Anggota Tim',
'有效用户人数': 'Jumlah Pengguna Efektif',
'节点用户人数': 'Jumlah Pengguna Node',
'个人持有金额': 'Jumlah Dana yang Dikelola Pribadi',
'团队业绩': 'Prestasi Tim',
'我的收益': 'Pendapatan Saya',
'查看明细': 'Lihat Rincian',
'团队明细': 'Rincian Tim',
'用户名称': 'Nama Pengguna',
'节点级别': 'Level Node',
'级别': 'Level',
'数量不能为0': 'Jumlah tidak boleh 0',
'销毁数量不能大于持有数量': 'Jumlah yang dihancurkan tidak boleh melebihi jumlah yang dimiliki',
'账户余额 AIC': 'Saldo Akun AIC',
'交易': 'Transaksi',
'账单': 'Tagihan',
'销毁数量': 'Jumlah yang Dihancurkan',
'产出数量': 'Jumlah yang Dihasilkan',
'AIC价格涨幅': 'Kenaikan Harga AIC',
'价格': 'Harga',
'24h涨幅比利': 'Kenaikan dalam 24 Jam',
'销毁挖矿': 'Penambangan dengan Penghancuran',
'挖矿秘籍': 'Tips Penambangan',
'输入销毁数量': 'Masukkan Jumlah yang Dihancurkan',
'闪兑记录': 'Catatan Flash Exchange',
'支付/数量': 'Pembayaran/Jumlah',
'得到/数量': 'Mendapatkan/Jumlah',
'手续费': 'Biaya Administrasi',
'时间': 'Waktu',
'兑换数量不能为空': 'Jumlah Pertukaran tidak boleh kosong',
'是否确认兑换': 'Apakah Anda yakin ingin menukar',
'支付': 'Pembayaran',
'充值数量': 'Jumlah Deposit',
'钱包余额': 'Saldo Dompet',
'得到': 'Mendapatkan',
'扣除手续费扣': 'Dikurangi Biaya Administrasi',
'理财规则': 'Aturan Keuangan',
'申请节点': 'Mendaftar Node',
'确定升级为': 'Apakah Anda yakin ingin meningkatkan ke',
'吗?申请节点的费用会直接\n从您的钱包账户直接划扣。': 'Biaya pendaftaran Node akan langsung ditarik dari akun dompet Anda.',
'个': 'unit',
'赠送': 'Diberikan',
'天': 'Hari',
'全网分红': 'Dividen Jaringan',
'运行天数': 'Jumlah Hari Beroperasi',
'昨日返佣（USDT）': 'Komisi Kemarin (USDT)',
'累计返佣（USDT）': 'Total Komisi (USDT)',
'节点详情': 'Detail Node',
'节点名称': 'Nama Node',
'利息奖励AIT': 'Penghargaan Bunga AIT',
'暂无数据': 'Tidak ada data',

'松开立即刷新': 'Lepaskan untuk Memuat Ulang',
'刷新完成': 'Pembaruan Selesai',
'刷新失败，请重试': 'Pembaruan Gagal, Silakan Coba Lagi',
'正在刷新数据中...': 'Memperbarui Data...',
'下拉可刷新': 'Tarik ke Bawah untuk Memuat Ulang',
'最後更新：今天': 'Terakhir Diperbarui: Hari Ini',
'正在加载更多的数据...': 'Memuat Data Tambahan...',
'已经全部加载完毕': 'Semua Data Telah Dimuat',
'加载失败...': 'Gagal Memuat...',
'松开立即加载更多': 'Lepaskan untuk Memuat Lebih Banyak',
'上拉可以加载更多': 'Tarik ke Atas untuk Memuat Lebih Banyak',

'恭喜您销毁成功': "Selamat atas keberhasilan penghancuran",
'挖矿倒计时': "Hitung mundur penambangan",
'小时': "jam",
'分': "menit",
'秒': "detik",
'您身边的\n智能理财专家': "Ahli keuangan\n pintar di sekitar Anda",
'邀请好友': "Undang teman",
'一起轻松交易数字货币': "Bersama-sama mudah bertransaksi mata uang digital",
"扣除手续费": "Potong biaya"

};
