final Map<String, String> intlEnVi = {
  "title":"首页",
  "setting language":"设置语言",
  "en":"英文",
  "cn":"简体",
  "hk":"繁体",
  '欢迎登录FUJL': "欢迎登录FUJL（越南）",

'投资': 'Đầu tư',
'邀请': 'Mời',
'我的': 'Của tôi',
'AI理财': 'Tài chính AI',

'节点': 'Nút',
'挖矿': 'Đào',
'闪兑': 'Trao đổi nhanh',
'团队': 'Đội',
'客服': 'Hỗ trợ khách hàng',

'智能理财': 'Quản lý tài sản thông minh',
'最大利率': 'Lãi suất tối đa',
'预计年化': 'Lợi suất ước tính hàng năm',
'申购限额': 'Hạn mức đăng ký mua',
'申购': 'Đăng ký mua',

  // 申购
 '第一期': 'Kỳ đầu',
'起息日期': 'Ngày bắt đầu tính lãi',
'申购额度': 'Hạn mức đăng ký mua',
'倍数起': 'Bội số tối thiểu',
'全部': 'Toàn bộ',
'账户余额': 'Số dư tài khoản',
'勾选并同意': 'Đánh dấu và đồng ý',
'利息奖励': 'Phần thưởng lãi',
'确认申购': 'Xác nhận đăng ký mua',
'温馨提示': 'Lời nhắc ấm áp',
'是否确认申购': 'Bạn có chắc muốn đăng ký mua không?',
'智能理财产品': 'Sản phẩm quản lý tài sản thông minh',
'取消': 'Hủy bỏ',
'确认': 'Xác nhận',
'申购额度格式不能为空': 'Hạn mức đăng ký mua không thể để trống',
'申购额度应大于': 'Hạn mức đăng ký mua phải lớn hơn',
'或小于': 'hoặc nhỏ hơn',
'申购额度应小于': 'Hạn mức đăng ký mua phải nhỏ hơn',
'格式不正确': 'Định dạng không chính xác',
'恭喜您申购成功': 'Chúc mừng bạn đã đăng ký mua thành công',
'选择币种': 'Chọn loại tiền tệ',
'AIT资产': 'Tài sản AIT',
'已确认': 'Đã xác nhận',
'账单明细': 'Chi tiết hóa đơn',
'AIT钱包余额': 'Số dư ví AIT',
'提示：1AIT=1USDT': 'Gợi ý: 1 AIT = 1 USDT',
'总收益(AIT)': 'Tổng thu nhập (AIT)',
'昨日收益（AIT）': 'Thu nhập ngày hôm qua (AIT)',
'剩余总量(AIT)': 'Tổng số lượng còn lại (AIT)',
'销毁数量（AIT）': 'Số lượng huỷ bỏ (AIT)',
'AIC账单': 'Hóa đơn AIC',
'全部月份': 'Tất cả các tháng',
'收入/支出': 'Thu nhập/Chi tiêu',

'节点认购': 'Mua cổ phần nút',
'AIC挖矿': 'Đào AIC',
'联系客服': 'Liên hệ dịch vụ khách hàng',

'邀请记录': 'Lịch sử mời',
'累计邀请好友': 'Tổng số bạn được mời',
'被邀请人': 'Người được mời',
'等级': 'Cấp độ',
'注册时间': 'Ngày đăng ký',
'名': 'Tên',
'查看更多': 'Xem thêm',

'暂定的banner': 'Banner tạm thời',
'收益明细': 'Chi tiết thu nhập',
'理财账户估值': 'Giá trị ước tính của tài khoản quản lý tài sản',
'理财⾦额（USDT）': 'Số tiền quản lý tài sản (USDT)',
'收益（AIT）': 'Thu nhập (AIT)',
'投资记录': 'Lịch sử đầu tư',

'收益名称': 'Tên thu nhập',
'当前收益': 'Thu nhập hiện tại',
'收益时间': 'Thời gian thu nhập',
'币种': 'Loại tiền tệ',
'当前利率': 'Lãi suất hiện tại',
'总收益': 'Tổng thu nhập',
'本金': 'Vốn gốc',
'起息日': 'Ngày bắt đầu tính lãi',
'状态': 'Trạng thái',

'推荐收益': 'Thu nhập từ giới thiệu',
'分红收益': 'Thu nhập từ cổ tức',
'租赁收益': 'Thu nhập từ thuê',
'节点收益': 'Thu nhập từ nút',
'分享收益': 'Thu nhập từ chia sẻ',
'团队收益': 'Thu nhập từ đội nhóm',
'我的收益明细': 'Chi tiết thu nhập của tôi',

 '我的团队': 'Đội nhóm của tôi',
'当前级别': 'Cấp độ hiện tại',
'团队人数': 'Số thành viên trong đội nhóm',
'有效用户人数': 'Số người dùng hợp lệ',
'节点用户人数': 'Số người dùng nút',
'个人持有金额': 'Số dư cá nhân',
'团队业绩': 'Thành tích đội nhóm',
'我的收益': 'Thu nhập của tôi',
'查看明细': 'Xem chi tiết',
'团队明细': 'Chi tiết đội nhóm',
'用户名称': 'Tên người dùng',
'节点级别': 'Cấp độ nút',
'级别': 'Cấp độ',
'数量不能为0': 'Số lượng không được là 0',
'销毁数量不能大于持有数量': 'Số lượng huỷ không thể lớn hơn số lượng hiện có',
'账户余额 AIC': 'Số dư tài khoản AIC',
'交易': 'Giao dịch',
'账单': 'Hóa đơn',
'销毁数量': 'Số lượng huỷ',
'产出数量': 'Số lượng sản xuất',
'AIC价格涨幅': 'Biến động giá AIC',
'价格': 'Giá',
'24h涨幅比利': 'Tỷ lệ tăng trong 24 giờ',
'销毁挖矿': 'Đào bằng huỷ',
'挖矿秘籍': 'Bí kíp đào',
'输入销毁数量': 'Nhập số lượng huỷ',
'闪兑记录': 'Lịch sử trao đổi nhanh',
'支付/数量': 'Thanh toán/Số lượng',
'得到/数量': 'Nhận/Số lượng',
'手续费': 'Phí giao dịch',
'时间': 'Thời gian',
'兑换数量不能为空': 'Số lượng trao đổi không thể để trống',
'是否确认兑换': 'Xác nhận trao đổi?',
'支付': 'Thanh toán',
'充值数量': 'Số lượng nạp',
'钱包余额': 'Số dư ví',
'得到': 'Nhận được',
'扣除手续费扣': 'Trừ phí giao dịch',
'理财规则': 'Quy tắc đầu tư',
'申请节点': 'Đăng ký nút',
'确定升级为': 'Xác nhận nâng cấp lên',
'吗?申请节点的费用会直接\n从您的钱包账户直接划扣。': 'Phải không? Phí đăng ký nút sẽ được trừ trực tiếp từ tài khoản ví của bạn.',
'个': 'cái',
'赠送': 'Tặng',
'天': 'ngày',
'全网分红': 'Phân chia lợi nhuận toàn mạng',
'运行天数': 'Số ngày hoạt động',
'昨日返佣（USDT）': 'Hoàn trả ngày hôm qua (USDT)',
'累计返佣（USDT）': 'Tổng hoàn trả (USDT)',
'节点详情': 'Chi tiết nút',
'节点名称': 'Tên nút',
'利息奖励AIT': 'Phần thưởng lãi suất AIT',
'暂无数据': 'Không có dữ liệu',

'松开立即刷新': 'Buông ra để làm mới ngay',
'刷新完成': 'Đã làm mới thành công',
'刷新失败，请重试': 'Làm mới thất bại, vui lòng thử lại',
'正在刷新数据中...': 'Đang làm mới dữ liệu...',
'下拉可刷新': 'Kéo xuống để làm mới',
'最後更新：今天': 'Cập nhật cuối: Hôm nay',
'正在加载更多的数据...': 'Đang tải thêm dữ liệu...',
'已经全部加载完毕': 'Đã tải tất cả',
'加载失败...': 'Tải thất bại...',
'松开立即加载更多': 'Buông ra để tải thêm ngay',
'上拉可以加载更多': 'Kéo lên để tải thêm',

'恭喜您销毁成功': "Chúc mừng bạn đã thành công trong việc phá hủy",
'挖矿倒计时': "Đếm ngược đào",
'小时': "giờ",
'分': "phút",
'秒': "giây",
'您身边的\n智能理财专家': "Chuyên gia tài\n chính thông minh của bạn",
'邀请好友': "Mời bạn bè",
'一起轻松交易数字货币': "Giao dịch tiền điện tử cùng nhau dễ dàng",
"扣除手续费": "Khấu trừ phí giao dịch",

};
