final Map<String, String> intlEnUS = {
  "title":"首页",
  "setting language":"设置语言",
  "en":"英文",
  "cn":"简体",
  "hk":"繁体",

  '欢迎登录FUJL': "欢迎登录FUJL（英语）",

'投资': 'Investment',
'邀请': 'Invite',
'我的': 'My',
'AI理财': 'AI Wealth Management',
'智能理财': 'Smart Wealth Management',
'最大利率': 'Maximum Interest Rate',
'预计年化': 'Estimated Annualized',
'申购限额': 'Subscription Limit',
'申购': 'Subscribe',

  // 申购
'第一期': 'First Phase',
'起息日期': 'Start Date',
'申购额度': 'Subscription Limit',
'倍数起': 'Starting Multiple',
'全部': 'All',
'账户余额': 'Account Balance',
'勾选并同意': 'Check and Agree',
'利息奖励': 'Interest Reward',
'确认申购': 'Confirm Subscription',
'温馨提示': 'Friendly Reminder',
'是否确认申购': 'Are you sure to subscribe?',
'智能理财产品': 'Smart Wealth Management Product',
'取消': 'Cancel',
'确认': 'Confirm',
'申购额度格式不能为空': 'Subscription limit format cannot be empty',
'申购额度应大于': 'Subscription limit should be greater than',
'或小于': 'or less than',
'申购额度应小于': 'Subscription limit should be less than',
'格式不正确': 'Incorrect format',
'恭喜您申购成功': 'Congratulations on your successful subscription',
'选择币种': 'Select Currency',
'AIT资产': 'AIT Assets',
'已确认': 'Confirmed',
'账单明细': 'Billing Details',
'AIT钱包余额': 'AIT Wallet Balance',
'提示：1AIT=1USDT': 'Note: 1AIT = 1USDT',
'总收益(AIT)': 'Total Earnings (AIT)',
'昨日收益（AIT）': "Yesterday's Earnings (AIT)",
'剩余总量(AIT)': 'Remaining Total Amount (AIT)',
'销毁数量（AIT）': 'Destroyed Quantity (AIT)',
'AIC账单': 'AIC Billing',
'全部月份': 'All Months',
'收入/支出': 'Income/Expenses',

'节点认购': 'Node',
'AIC挖矿': 'AIC Mining',
'闪兑': 'Swap',
'团队': 'Team',
'客服': 'Service',

'邀请记录': 'Invitation Records',
'累计邀请好友': 'Total Invited Friends',
'被邀请人': 'Invited Person',
'等级': 'Level',
'注册时间': 'Registration Time',
'名': 'Name',
'查看更多': 'View More',

'暂定的banner': 'Temporary Banner',
'收益明细': 'Earnings Details',
'理财账户估值': 'Wealth Account Valuation',
'理财⾦额（USDT）': 'Wealth Amount (USDT)',
'收益（AIT）': 'Earnings (AIT)',
'投资记录': 'Investment Records',

'收益名称': 'Earnings Name',
'当前收益': 'Current Earnings',
'收益时间': 'Earnings Time',
'币种': 'Currency',
'当前利率': 'Current Interest Rate',
'总收益': 'Total Earnings',
'本金': 'Principal',
'起息日': 'Start Date',
'状态': 'Status',

'推荐收益': 'Referral Earnings',
'分红收益': 'Dividend Earnings',
'租赁收益': 'Lease Earnings',
'节点收益': 'Node Earnings',
'分享收益': 'Sharing Earnings',
'团队收益': 'Team Earnings',
'我的收益明细': 'My Earnings Details',

  '我的团队': 'My Team',
'当前级别': 'Current Level',
'团队人数': 'Team Size',
'有效用户人数': 'Active User Count',
'节点用户人数': 'Node User Count',
'个人持有金额': 'Personal Holdings',
'团队业绩': 'Team Performance',
'我的收益': 'My Earnings',
'查看明细': 'View Details',
'团队明细': 'Team Details',
'用户名称': 'User Name',
'节点级别': 'Node Level',
'级别': 'Level',
'数量不能为0': 'Quantity cannot be 0',
'销毁数量不能大于持有数量': 'Destruction quantity cannot exceed holding quantity',
'账户余额 AIC': 'Account Balance AIC',
'交易': 'Transactions',
'账单': 'Bill',
'销毁数量': 'Destruction Quantity',
'产出数量': 'Output Quantity',
'AIC价格涨幅': 'AIC Price Increase',
'价格': 'Price',
'24h涨幅比利': '24h Increase Ratio',
'销毁挖矿': 'Destruction Mining',
'挖矿秘籍': 'Mining Tips',
'输入销毁数量': 'Enter Destruction Quantity',
'闪兑记录': 'Flash Exchange Records',
'支付/数量': 'Payment/Quantity',
'得到/数量': 'Received/Quantity',
'手续费': 'Transaction Fee',
'时间': 'Time',
'兑换数量不能为空': 'Exchange quantity cannot be empty',
'是否确认兑换': 'Confirm Exchange?',
'支付': 'Payment',
'充值数量': 'Recharge Quantity',
'钱包余额': 'Wallet Balance',
'得到': 'Received',
'扣除手续费扣': 'Deducted Transaction Fee',
'理财规则': 'Financial Rules',
'申请节点': 'Apply for Node',
'确定升级为': 'Confirm Upgrade to',
'吗?申请节点的费用会直接\n从您的钱包账户直接划扣。': 'Are you sure to upgrade to? The fee for applying for a node will be deducted directly from your wallet account.',
'个': 'pieces',
'赠送': 'Gift',
'天': 'days',
'全网分红': 'Network-wide Dividends',
'节点': 'Node',
'运行天数': 'Running Days',
'昨日返佣（USDT）': "Yesterday's Commission (USDT)",
'累计返佣（USDT）': 'Accumulated Commission (USDT)',
'节点详情': 'Node Details',
'节点名称': 'Node Name',
'利息奖励AIT': 'Interest Reward AIT',
'暂无数据': 'No Data',

'松开立即刷新': 'Release to Refresh',
'刷新完成': 'Refresh Completed',
'刷新失败，请重试': 'Refresh Failed, Please Retry',
'正在刷新数据中...': 'Refreshing Data...',
'下拉可刷新': 'Pull Down to Refresh',
'最後更新：今天': 'Last Updated: Today',
'正在加载更多的数据...': 'Loading More Data...',
'已经全部加载完毕': 'All Data Loaded',
'加载失败...': 'Load Failed...',
'松开立即加载更多': 'Release to Load More',
'上拉可以加载更多': 'Pull Up to Load More',

'恭喜您销毁成功': "Congratulations on successful destruction",
'挖矿倒计时': "Mining countdown",
'小时': "hours",
'分': "minutes",
'秒': "seconds",
'您身边的\n智能理财专家': "Your smart \nfinancial expert",
'邀请好友': "Invite friends",
'一起轻松交易数字货币': "Trade cryptocurrencies together with ease",
"扣除手续费": "Deduct transaction fee"

};
