final Map<String, String> intlEnFr = {
  "title":"首页",
  "setting language":"设置语言",
  "en":"英文",
  "cn":"简体",
  "hk":"繁体",
  '欢迎登录FUJL': "欢迎登录FUJL（法语）",

'投资': 'Investir',
'邀请': 'Inviter',
'我的': 'Mon',
'AI理财': 'Finances AI',
'节点': 'Nœud',
'挖矿': 'Miner',
'闪兑': 'Échange',
'团队': 'Équipe',
'客服': 'Service client',

'智能理财': 'Gestion intelligente',
'最大利率': 'Taux maximum',
'预计年化': 'Rendement annuel estimé',
'申购限额': "Limite d'achat",
'申购': 'Acheter',

  // 申购
'第一期': 'Première phase',
'起息日期': "Date de début d'intérêts",
'申购额度': 'Montant de souscription',
'倍数起': 'Multiples',
'全部': 'Tout',
'账户余额': 'Solde du compte',
'勾选并同意': 'Cochez et acceptez',
'利息奖励': "Récompense d'intérêt",
'确认申购': 'Confirmer la souscription',
'温馨提示': 'Conseil chaleureux',
'是否确认申购': 'Confirmez-vous la souscription ?',
'智能理财产品': 'Produit de gestion intelligente',
'取消': 'Annuler',
'确认': 'Confirmer',
'申购额度格式不能为空': 'Le format du montant de souscription ne peut pas être vide',
'申购额度应大于': 'Le montant de souscription doit être supérieur à',
'或小于': 'ou inférieur à',
'申购额度应小于': 'Le montant de souscription doit être inférieur à',
'格式不正确': 'Format incorrect',
'恭喜您申购成功': 'Félicitations pour votre souscription réussie',
'选择币种': 'Sélectionnez la devise',
'AIT资产': 'Actifs AIT',
'已确认': 'Confirmé',
'账单明细': 'Détails de la facture',
'AIT钱包余额': 'Solde du portefeuille AIT',
'提示：1AIT=1USDT': 'Remarque : 1AIT = 1USDT',
'总收益(AIT)': 'Bénéfice total (AIT)',
'昨日收益（AIT）': "Bénéfice d'hier (AIT)",
'剩余总量(AIT)': 'Quantité totale restante (AIT)',
'销毁数量（AIT）': 'Quantité détruite (AIT)',
'AIC账单': 'Facture AIC',
'全部月份': 'Tous les mois',
'收入/支出': 'Revenus/Dépenses',

'节点认购': 'Souscription de nœud',
'AIC挖矿': 'Minage AIC',
'联系客服': 'Contactez le service clientèle',

'邀请记录': 'Historique des invitations',
'累计邀请好友': 'Amis invités accumulés',
'被邀请人': 'Personne invitée',
'等级': 'Niveau',
'注册时间': "Date d'inscription",
'名': 'Nom',
'查看更多': 'Voir plus',

'暂定的banner': 'Bannière provisoire',
'收益明细': 'Détails des revenus',
'理财账户估值': 'Évaluation du compte de gestion',
'理财⾦额（USDT）': 'Montant de gestion (USDT)',
'收益（AIT）': 'Revenus (AIT)',
'投资记录': "Historique d'investissement",

'收益名称': 'Nom des revenus',
'当前收益': 'Revenu actuel',
'收益时间': 'Heure des revenus',
'币种': 'Devise',
'当前利率': 'Taux actuel',
'总收益': 'Revenus totaux',
'本金': 'Capital',
'起息日': 'Date de départ',
'状态': 'Statut',

'推荐收益': 'Revenus de recommandation',
'分红收益': 'Revenus de dividendes',
'租赁收益': 'Revenus de location',
'节点收益': 'Revenus de nœuds',
'分享收益': 'Revenus de partage',
'团队收益': "Revenus d'équipe",
'我的收益明细': 'Mes détails de revenus',

'我的团队': 'Mon équipe',
'当前级别': 'Niveau actuel',
'团队人数': "Nombre d'équipe",
'有效用户人数': "Nombre d'utilisateurs actifs",
'节点用户人数': "Nombre d'utilisateurs de nœuds",
'个人持有金额': 'Montant détenu individuellement',
'团队业绩': "Performance de l'équipe",
'我的收益': 'Mes revenus',
'查看明细': 'Voir les détails',
'团队明细': "Détails de l'équipe",
'用户名称': "Nom d'utilisateur",
'节点级别': 'Niveau du nœud',
'级别': 'Niveau',
'数量不能为0': 'La quantité ne peut pas être 0',
'销毁数量不能大于持有数量': 'La quantité détruite ne peut pas être supérieure à la quantité détenue',
'账户余额 AIC': 'Solde du compte AIC',
'交易': 'Transaction',
'账单': 'Facture',
'销毁数量': 'Quantité détruite',
'产出数量': 'Quantité produite',
'AIC价格涨幅': "Fluctuation du prix de l'AIC",
'价格': 'Prix',
'24h涨幅比利': 'Fluctuation de 24 heures',
'销毁挖矿': 'Minage par destruction',
'挖矿秘籍': 'Guide de minage',
'输入销毁数量': 'Entrez la quantité à détruire',
'闪兑记录': "Historique d'échange instantané",
'支付/数量': 'Paiement/Quantité',
'得到/数量': 'Obtenu/Quantité',
'手续费': 'Frais de transaction',
'时间': 'Temps',
'兑换数量不能为空': 'La quantité de conversion ne peut pas être vide',
'是否确认兑换': 'Confirmer la conversion?',
'支付': 'Paiement',
'充值数量': 'Quantité de recharge',
'钱包余额': 'Solde du portefeuille',
'得到': 'Obtenir',
'扣除手续费扣': 'Déduction des frais',
'理财规则': 'Règles de gestion financière',
'申请节点': 'Demander un nœud',
'确定升级为': 'Confirmer la mise à niveau vers',
'吗?申请节点的费用会直接\n从您的钱包账户直接划扣。': '? Les frais de demande de nœud seront déduits directement de votre compte de portefeuille.',
'个': 'Nombre',
'赠送': 'Cadeau',
'天': 'Jours',
'全网分红': 'Bonus global',
'运行天数': "Durée d'exécution",
'昨日返佣（USDT）': 'Commission de retour hier (USDT)',
'累计返佣（USDT）': 'Commission totale (USDT)',
'节点详情': 'Détails du nœud',
'节点名称': 'Nom du nœud',
'利息奖励AIT': "Récompense d'intérêt AIT",
'暂无数据': 'Aucune donnée disponible',
'松开立即刷新': 'Relâchez pour rafraîchir',
'刷新完成': 'Rafraîchissement terminé',
'刷新失败，请重试': 'Échec du rafraîchissement. Veuillez réessayer',
'正在刷新数据中...': 'Actualisation des données en cours...',
'下拉可刷新': 'Tirez vers le bas pour rafraîchir',
'最後更新：今天': "Dernière mise à jour : aujourd'hui",
'正在加载更多的数据...': 'Chargement de plus de données en cours...',
'已经全部加载完毕': 'Toutes les données ont été chargées',
'加载失败...': 'Échec du chargement...',
'松开立即加载更多': 'Relâchez pour charger plus',
'上拉可以加载更多': 'Tirez vers le haut pour charger plus',

'恭喜您销毁成功': "Félicitations pour la destruction réussie",
'挖矿倒计时': "Compte à rebours du minage",
'小时': "heures",
'分': "minutes",
'秒': "secondes",
'您身边的\n智能理财专家': "Votre expert\n en gestion financière",
'邀请好友': "Inviter des amis",
'一起轻松交易数字货币': "Échangez facilement des cryptomonnaies ensemble",
"扣除手续费": "Déduire les frais"
};
