final Map<String, String> intlEnEd = {
  "title":"首页",
  "setting language":"设置语言",
  "en":"英文",
  "cn":"简体",
  "hk":"繁体",
  '欢迎登录FUJL': "欢迎登录FUJL（德语）",

'投资': 'Investieren',
'邀请': 'Einladen',
'我的': 'Mein',
'AI理财': 'AI Finanzen',
'节点': 'Knoten',
'挖矿': 'Minen',
'闪兑': 'Tauschen',
'团队': 'Team',
'客服': 'Kundenservice',

'智能理财': 'Intelligente Finanzierung',
'最大利率': 'Maximaler Zinssatz',
'预计年化': 'Voraussichtliche Rendite',
'申购限额': 'Kaufbegrenzung',
'申购': 'Kaufen',

  // 申购
'第一期': 'Erste Phase',
'起息日期': 'Zinsdatum',
'申购额度': 'Kauflimit',
'倍数起': 'Multiplikator Start',
'全部': 'Alle',
'账户余额': 'Kontostand',
'勾选并同意': 'Ankreuzen und zustimmen',
'利息奖励': 'Zinsprämie',
'确认申购': 'Kauf bestätigen',
'温馨提示': 'Hinweis',
'是否确认申购': 'Kauf bestätigen?',
'智能理财产品': 'Intelligentes Finanzprodukt',
'取消': 'Abbrechen',
'确认': 'Bestätigen',
'申购额度格式不能为空': 'Kauflimit darf nicht leer sein',
'申购额度应大于': 'Kauflimit sollte größer als',
'或小于': 'oder kleiner als',
'申购额度应小于': 'Kauflimit sollte kleiner als',
'格式不正确': 'Ungültiges Format',
'恭喜您申购成功': 'Herzlichen Glückwunsch zum erfolgreichen Kauf',
'选择币种': 'Währung auswählen',
'AIT资产': 'AIT-Vermögenswert',
'已确认': 'Bestätigt',
'账单明细': 'Rechnungsdetails',
'AIT钱包余额': 'AIT Wallet-Guthaben',
'提示：1AIT=1USDT': 'Hinweis: 1AIT = 1USDT',
'总收益(AIT)': 'Gesamteinkommen (AIT)',
'昨日收益（AIT）': 'Gestriges Einkommen (AIT)',
'剩余总量(AIT)': 'Verbleibende Gesamtmenge (AIT)',
'销毁数量（AIT）': 'Zerstörte Menge (AIT)',
'AIC账单': 'AIC-Rechnung',
'全部月份': 'Alle Monate',
'收入/支出': 'Einnahmen/Ausgaben',

'节点认购': 'Knotenabonnement',
'AIC挖矿': 'AIC-Mining',
'联系客服': 'Kundenservice kontaktieren',

'邀请记录': 'Einladungsverlauf',
'累计邀请好友': 'Gesamtzahl der eingeladenen Freunde',
'被邀请人': 'Eingeladene Person',
'等级': 'Stufe',
'注册时间': 'Registrierungsdatum',
'名': 'Name',
'查看更多': 'Mehr anzeigen',

 '暂定的banner': 'Vorläufiges Banner',
'收益明细': 'Gewinn-Details',
'理财账户估值': 'Bewertung des Anlagekontos',
'理财⾦额（USDT）': 'Anlagebetrag (USDT)',
'收益（AIT）': 'Gewinn (AIT)',
'投资记录': 'Investitionsaufzeichnungen',

'收益名称': 'Gewinnname',
'当前收益': 'Aktueller Gewinn',
'收益时间': 'Gewinnzeit',
'币种': 'Währung',
'当前利率': 'Aktueller Zinssatz',
'总收益': 'Gesamtgewinn',
'本金': 'Hauptbetrag',
'起息日': 'Beginndatum der Verzinsung',
'状态': 'Status',

'推荐收益': 'Empfehlungsgewinn',
'分红收益': 'Dividendengewinn',
'租赁收益': 'Mietgewinn',
'节点收益': 'Knotengewinn',
'分享收益': 'Gewinn durch Teilen',
'团队收益': 'Teamgewinn',
'我的收益明细': 'Meine Gewinn-Details',

'我的团队': 'Mein Team',
'当前级别': 'Aktuelles Level',
'团队人数': 'Anzahl des Teams',
'有效用户人数': 'Anzahl der aktiven Benutzer',
'节点用户人数': 'Anzahl der Knotenbenutzer',
'个人持有金额': 'Persönlicher Besitzbetrag',
'团队业绩': 'Teamleistung',
'我的收益': 'Mein Gewinn',
'查看明细': 'Details anzeigen',
'团队明细': 'Teamdetails',
'用户名称': 'Benutzername',
'节点级别': 'Knotenlevel',
'级别': 'Level',
'数量不能为0': 'Die Anzahl darf nicht 0 sein',
'销毁数量不能大于持有数量': 'Die zu vernichtende Menge darf nicht größer als der Bestand sein',
'账户余额 AIC': 'Kontostand AIC',
'交易': 'Transaktionen',
'账单': 'Abrechnung',
'销毁数量': 'Zu vernichtende Menge',
'产出数量': 'Produzierte Menge',
'AIC价格涨幅': 'AIC-Preisanstieg',
'价格': 'Preis',
'24h涨幅比利': '24-Stunden-Renditeverhältnis',
'销毁挖矿': 'Vernichtungs-Mining',
'挖矿秘籍': 'Mining-Leitfaden',
'输入销毁数量': 'Geben Sie die zu vernichtende Menge ein',
'闪兑记录': 'Aufzeichnungen der schnellen Konvertierung',
'支付/数量': 'Zahlung/Menge',
'得到/数量': 'Erhalten/Menge',
'手续费': 'Gebühr',
'时间': 'Zeit',
'兑换数量不能为空': 'Die Konvertierungsmenge darf nicht leer sein',

'是否确认兑换': 'Möchten Sie den Umtausch bestätigen?',
'支付': 'Bezahlen',
'充值数量': 'Aufladebetrag',
'钱包余额': 'Wallet-Guthaben',
'得到': 'Erhalten',
'扣除手续费扣': 'Abzüglich Gebühren',
'理财规则': 'Finanzregeln',
'申请节点': 'Knoten beantragen',
'确定升级为': 'Sind Sie sicher, dass Sie aufstufen möchten zu',
'吗?申请节点的费用会直接\n从您的钱包账户直接划扣。': '? Die Kosten für die Beantragung eines Knotens werden direkt von Ihrem Wallet-Konto abgebucht.',
'个': 'Stück',
'赠送': 'Geschenk',
'天': 'Tage',
'全网分红': 'Globale Dividenden',
'运行天数': 'Laufzeit in Tagen',
'昨日返佣（USDT）': 'Gestern erhalten (USDT)',
'累计返佣（USDT）': 'Kumulativ erhalten (USDT)',
'节点详情': 'Knotendetails',
'节点名称': 'Knotenname',
'利息奖励AIT': 'Zinsbelohnung AIT',
'暂无数据': 'Keine Daten',

'松开立即刷新': 'Loslassen, um sofort zu aktualisieren',
'刷新完成': 'Aktualisierung abgeschlossen',
'刷新失败，请重试': 'Aktualisierung fehlgeschlagen, bitte erneut versuchen',
'正在刷新数据中...': 'Daten werden aktualisiert...',
'下拉可刷新': 'Zum Aktualisieren nach unten ziehen',
'最後更新：今天': 'Zuletzt aktualisiert: Heute',
'正在加载更多的数据...': 'Weitere Daten werden geladen...',
'已经全部加载完毕': 'Alle Daten wurden geladen',
'加载失败...': 'Fehler beim Laden...',
'松开立即加载更多': 'Loslassen, um mehr zu laden',
'上拉可以加载更多': 'Nach oben ziehen, um mehr zu laden',

'恭喜您销毁成功': "Herzlichen Glückwunsch zur erfolgreichen Zerstörung",
'挖矿倒计时': "Mining Countdown",
'小时': "Stunden",
'分': "Minuten",
'秒': "Sekunden",
'您身边的\n智能理财专家': "Ihr persönlicher \nFinanzexperte",
'邀请好友': "Freunde einladen",
'一起轻松交易数字货币': "Gemeinsam einfach mit digitalen Währungen handeln",
"扣除手续费": "Gebühren abziehen"
};
