final Map<String, String> intlEnEs = {
  "title":"首页",
  "setting language":"设置语言",
  "en":"英文",
  "cn":"简体",
  "hk":"繁体",
  '欢迎登录FUJL': "欢迎登录FUJL（西班牙）",

'投资': 'Invertir',
'邀请': 'Invitar',
'我的': 'Mi',
'AI理财': 'Finanzas AI',
'节点': 'Nodo',
'挖矿': 'Minar',
'闪兑': 'Intercambiar',
'团队': 'Equipo',
'客服': 'Servicio de atención al cliente',

'智能理财': 'Finanzas Inteligentes',
'最大利率': 'Tasa Máxima',
'预计年化': 'Rentabilidad Anual Estimada',
'申购限额': 'Límite de Compra',
'申购': 'Comprar',

  // 申购
'第一期': 'Primera fase',
'起息日期': 'Fecha de inicio de interés',
'申购额度': 'Límite de compra',
'倍数起': 'Múltiplo mínimo',
'全部': 'Todo',
'账户余额': 'Saldo de la cuenta',
'勾选并同意': 'Seleccionar y aceptar',
'利息奖励': 'Recompensa de intereses',
'确认申购': 'Confirmar compra',
'温馨提示': 'Consejo amable',
'是否确认申购': '¿Está seguro de confirmar la compra?',
'智能理财产品': 'Producto de Finanzas Inteligentes',
'取消': 'Cancelar',
'确认': 'Confirmar',
'申购额度格式不能为空': 'El formato del límite de compra no puede estar vacío',
'申购额度应大于': 'El límite de compra debe ser mayor que',
'或小于': 'o menor que',
'申购额度应小于': 'El límite de compra debe ser menor que',
'格式不正确': 'Formato incorrecto',
'恭喜您申购成功': '¡Felicidades por su compra exitosa!',
'选择币种': 'Seleccionar moneda',
'AIT资产': 'Activos AIT',
'已确认': 'Confirmado',
'账单明细': 'Detalles de la factura',
'AIT钱包余额': 'Saldo de la billetera AIT',
'提示：1AIT=1USDT': 'Consejo: 1 AIT = 1 USDT',
'总收益(AIT)': 'Ganancia total (AIT)',
'昨日收益（AIT）': 'Ganancia de ayer (AIT)',
'剩余总量(AIT)': 'Cantidad total restante (AIT)',
'销毁数量（AIT）': 'Cantidad de destrucción (AIT)',
'AIC账单': 'Factura de AIC',
'全部月份': 'Todos los meses',
'收入/支出': 'Ingreso/Gasto',

'节点认购': 'Suscripción de nodo',
'AIC挖矿': 'Minería de AIC',
'联系客服': 'Contactar servicio al cliente',

'邀请记录': 'Registro de invitaciones',
'累计邀请好友': 'Total de amigos invitados',
'被邀请人': 'Persona invitada',
'等级': 'Nivel',
'注册时间': 'Fecha de registro',
'名': 'Nombre',
'查看更多': 'Ver más',

'暂定的banner': 'Banner provisional',
'收益明细': 'Detalles de ganancias',
'理财账户估值': 'Valoración de cuenta de finanzas',
'理财⾦额（USDT）': 'Cantidad de finanzas (USDT)',
'收益（AIT）': 'Ganancia (AIT)',
'投资记录': 'Historial de inversiones',

'收益名称': 'Nombre de ganancias',
'当前收益': 'Ganancia actual',
'收益时间': 'Fecha de ganancia',
'币种': 'Moneda',
'当前利率': 'Tasa de interés actual',
'总收益': 'Ganancia total',
'本金': 'Capital',
'起息日': 'Fecha de inicio de interés',
'状态': 'Estado',

'推荐收益': 'Ganancias de recomendación',
'分红收益': 'Ganancias de dividendos',
'租赁收益': 'Ganancias de alquiler',
'节点收益': 'Ganancias de nodo',
'分享收益': 'Ganancias de compartición',
'团队收益': 'Ganancias de equipo',
'我的收益明细': 'Mis detalles de ganancias',

  
'我的团队': 'Mi equipo',
'当前级别': 'Nivel actual',
'团队人数': 'Cantidad de personas en el equipo',
'有效用户人数': 'Cantidad de usuarios activos',
'节点用户人数': 'Cantidad de usuarios de nodo',
'个人持有金额': 'Cantidad de dinero personal',
'团队业绩': 'Rendimiento del equipo',
'我的收益': 'Mis ganancias',
'查看明细': 'Ver detalles',
'团队明细': 'Detalles del equipo',
'用户名称': 'Nombre de usuario',
'节点级别': 'Nivel de nodo',
'级别': 'Nivel',
'数量不能为0': 'La cantidad no puede ser cero',
'销毁数量不能大于持有数量': 'La cantidad de destrucción no puede ser mayor que la cantidad en posesión',
'账户余额 AIC': 'Saldo de cuenta AIC',
'交易': 'Transacciones',
'账单': 'Facturas',
'销毁数量': 'Cantidad de destrucción',
'产出数量': 'Cantidad generada',
'AIC价格涨幅': 'Variación de precio de AIC',
'价格': 'Precio',
'24h涨幅比利': 'Variación de 24 horas',
'销毁挖矿': 'Minería de destrucción',
'挖矿秘籍': 'Guía de minería',
'输入销毁数量': 'Ingrese la cantidad de destrucción',
'闪兑记录': 'Registro de intercambio instantáneo',
'支付/数量': 'Pago/Cantidad',
'得到/数量': 'Obtenido/Cantidad',
'手续费': 'Tarifa',
'时间': 'Tiempo',
'兑换数量不能为空': 'La cantidad de intercambio no puede estar vacía',
'是否确认兑换': '¿Confirmar el intercambio?',
'支付': 'Pago',
'充值数量': 'Cantidad de recarga',
'钱包余额': 'Saldo de la billetera',
'得到': 'Obtenido',
'扣除手续费扣': 'Descontar tarifa',
'理财规则': 'Reglas de inversión',
'申请节点': 'Solicitar nodo',
'确定升级为': '¿Confirmar la actualización a',
'吗?申请节点的费用会直接\n从您的钱包账户直接划扣。': '¿?Los gastos de solicitud de nodo se deducirán directamente de su cuenta de billetera.',
'个': 'Cantidad',
'赠送': 'Regalar',
'天': 'Día',
'全网分红': 'Dividendos totales de la red',
'运行天数': 'Días de funcionamiento',
'昨日返佣（USDT）': 'Comisiones de ayer (USDT)',
'累计返佣（USDT）': 'Comisiones acumuladas (USDT)',
'节点详情': 'Detalles del nodo',
'节点名称': 'Nombre del nodo',
'利息奖励AIT': 'Recompensa de intereses AIT',
'暂无数据': 'No hay datos disponibles',

'松开立即刷新': 'Suelta para actualizar de inmediato',
'刷新完成': 'Actualización completada',
'刷新失败，请重试': 'Error al actualizar, por favor inténtalo de nuevo',
'正在刷新数据中...': 'Actualizando datos...',
'下拉可刷新': 'Desliza hacia abajo para actualizar',
'最後更新：今天': 'Última actualización: hoy',
'正在加载更多的数据...': 'Cargando más datos...',
'已经全部加载完毕': 'Todos los datos han sido cargados',
'加载失败...': 'Error al cargar, por favor inténtalo de nuevo',
'松开立即加载更多': 'Suelta para cargar más de inmediato',
'上拉可以加载更多': 'Desliza hacia arriba para cargar más',


'恭喜您销毁成功': "Felicidades por la destrucción exitosa",
'挖矿倒计时': "Cuenta regresiva de minería",
'小时': "horas",
'分': "minutos",
'秒': "segundos",
'您身边的\n智能理财专家': "Su asesor de\n finanzas inteligente",
'邀请好友': "Invitar amigos",
'一起轻松交易数字货币': "Comercio fácil de criptomonedas juntos",
"扣除手续费": "Deducir tarifa"
};
